### ISSUE TITLE
Kotlin highlighting issues

### ISSUE THREAD

**Issue by vanniktech** [romannurik/SlidesCodeHighlighter#15]
So far I've found two highlighting issues.

String interpolation is not highlighted:

<img width="541" alt="screen shot 2018-06-05 at 14 29 27" src="https://user-images.githubusercontent.com/5759366/40992109-1e2970d6-68f6-11e8-8817-f32b0dd5ff1d.png">

Numbers in function names are highlighted differently:

<img width="179" alt="screen shot 2018-06-05 at 14 29 44" src="https://user-images.githubusercontent.com/5759366/40992136-2d73208c-68f6-11e8-8924-221e64cf9aec.png">

**Comment by romannurik** [comment]
Hey there! All the actual syntax highlighting/parsing is done by [code-prettify](https://github.com/google/code-prettify); do you know if this highlights correctly w/ that tool? If not it may be good to file against that issue tracker. Also I assume this is for Kotlin..

**Comment by vanniktech** [comment]
There's no easy way to check for me online - like on a sample page, right? I've searched the repo but could not find anything.

**Comment by romannurik** [comment]
I put together a quick demo here:
http://jsfiddle.net/k0en3rLm/

**Comment by vanniktech** [comment]
Thanks for that. I've opened a few issues on their side:

https://github.com/google/code-prettify/issues/548
https://github.com/google/code-prettify/issues/549
https://github.com/google/code-prettify/issues/550
https://github.com/google/code-prettify/issues/551

**Comment by romannurik** [comment]
Awesome thanks! As soon as those are fixed I can update this repo and app with the latest :)
