### ISSUE TITLE
Ruby Support

### ISSUE THREAD

**Issue by FunkyloverOne** [romannurik/SlidesCodeHighlighter#16]
Hey! It would be nice to also have proper Ruby syntax highlighting :)

**Comment by romannurik** [comment]
If you pasted Ruby code and leave language at auto-detect does it work OK? If so it may be as simple as adding a Ruby language item to the menu

**Comment by romannurik** [comment]
So the syntax highlighting itself is done by [code-prettify](https://github.com/google/code-prettify), and I just ran a quick test forcing the language to 'Ruby' and it looks like this is the best we can do for now:

http://jsfiddle.net/28q3drhz/

In case you do want to follow up on this, I'd consider filing a bug to support interpolation and other Ruby language features there!
