### ISSUE TITLE
Enable actual highlighting 

### ISSUE THREAD

**Issue by JoseAlcerreca** [romannurik/SlidesCodeHighlighter#19]
It would be great to be able to select a word or some lines of code and wrap them in `<bold>`.

**Comment by romannurik** [comment]
Ah, subhighlighting in some way would indeed be cool. I'd love to accept a PR for this!

**Comment by romannurik** [comment]
Started on this, finally :)

**Comment by romannurik** [comment]
Shipped! https://twitter.com/romannurik/status/1209154658788397059
