### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by PaulWoitaschek** [romannurik/SlidesCodeHighlighter#2]
It would be great to have kotlin support.

**Comment by romannurik** [comment]
Blocked on [Google Code Prettify](https://github.com/google/code-prettify) supporting it :)

**Comment by yigit** [comment]
looks like it is there now :) https://github.com/google/code-prettify/issues/491

**Comment by romannurik** [comment]
Just merged in @yigit's PR #10. Will test and push.

**Comment by romannurik** [comment]
Pushed
