### ISSUE TITLE
Kotlin colors underscores differently in constants

### ISSUE THREAD

**Issue by odbol** [romannurik/SlidesCodeHighlighter#26]
Enter this code: 

```
val vibrator = context.getSystemService(Context.VIBRATOR_SERVICE) as Vibrator
```

Observed:

The underscore "_" in "VIBRATOR_SERVICE" is yellow when the rest of the symbol is white.

Expected:

The entire symbol "VIBRATOR_SERVICE" should all be one color (white).

**Comment by romannurik** [comment]
hm weird... but you may want to file this in [this repo](https://github.com/google/code-prettify) since that's the highlighter we use
