### ISSUE TITLE
Fine a theme used in SlidesCodeHighlighter

### ISSUE THREAD

**Issue by lewwns** [romannurik/SlidesCodeHighlighter#30]
What is the theme of  ```#io19```  used in [SlidesCodeHighlighter](https://romannurik.github.io/SlidesCodeHighlighter/)
It looks useful and fascinating.
note: for Kotlin users. Thanks a lot!

**Comment by romannurik** [comment]
I'm not sure what you mean? Do you mean how do you get this theme in other editors? This was a custom-made theme from the Google colors for Google I/O 2019.

**Comment by lewwns** [comment]
Just wanted to know the detail of this theme, like the name/title or the exact file that can be imported in different coding platforms. I'd like to import this theme to my Android Studio. Do you have this kind of information? Thanks for your time!

**Comment by romannurik** [comment]
Not really, it's custom. But you can see the source code for the theme here:
https://github.com/romannurik/SlidesCodeHighlighter/blob/master/themes.js#L147
