### ISSUE TITLE
Pasting into Google Slides only preserves colors, neither font nor font size, and inserts very wide spaces between lines

### ISSUE THREAD

**Issue by leventov** [romannurik/SlidesCodeHighlighter#41]
![image](https://user-images.githubusercontent.com/609240/71555126-4a85b300-2a39-11ea-9957-ed33604a29ae.png)

![image](https://user-images.githubusercontent.com/609240/71555131-5b362900-2a39-11ea-912d-1d3b20f68dfb.png)

Am I doing something wrong? Is there a special way in how the code should be copied from the webapp to Google Slides?

**Comment by romannurik** [comment]
For fonts, you'll need to enable the fonts in Slides first (IIRC it's called "More Fonts...")

For line spacing, this can be finicky... I tend to adjust it in Slides after pasting.

For font size, Slides does a conversion from px to something like pt. There's a bug open around that and I've considered having the field let you control the final type size vs the size in pixels :-/

**Comment by leventov** [comment]
Thanks for help!
