### ISSUE TITLE
Doesn't handle JSX very well :(

### ISSUE THREAD

**Issue by yefim** [romannurik/SlidesCodeHighlighter#42]
What it looks like:

<img width="1552" alt="Screen Shot 2020-01-23 at 1 56 40 AM" src="https://user-images.githubusercontent.com/1170843/72962885-99e2a900-3d83-11ea-8a4d-2a78ce8352ae.png">

What I expect it to look like: 

<img width="486" alt="Screen Shot 2020-01-23 at 1 57 07 AM" src="https://user-images.githubusercontent.com/1170843/72962906-aa931f00-3d83-11ea-96e1-c3f5cbfb6300.png">

**Comment by romannurik** [comment]
google-code-prettify doesn't handle JSX :-/ this would be resolved if we switched to another syntax highlighter like Ace or Prism potentially.

**Comment by romannurik** [comment]
The `prism` branch fixes this... hoping to merge in the coming weeks.
