### ISSUE TITLE
ES6 string literals are not highlighted

### ISSUE THREAD

**Issue by lennertVanSever** [romannurik/SlidesCodeHighlighter#43]
When using a JavaScript ES6 string literal, the variables within the string literal are not highlighted

Current result:
<img width="468" alt="Screenshot 2020-03-01 at 18 22 50" src="https://user-images.githubusercontent.com/23064517/75630305-dce93500-5be9-11ea-8c41-dd5717358a13.png">

What I expected:
<img width="440" alt="Screenshot 2020-03-01 at 18 24 50" src="https://user-images.githubusercontent.com/23064517/75630317-f5f1e600-5be9-11ea-86ce-8ed2a2e9c633.png">

**Comment by romannurik** [comment]
Yeah this would be very nice but currently requires a switch to another
highlighting engine such as Prism.

**Comment by romannurik** [comment]
The `prism` branch fixes this... hoping to merge in the coming weeks.
