### ISSUE TITLE
Export as images?

### ISSUE THREAD

**Issue by MasterScrat** [romannurik/SlidesCodeHighlighter#44]
It is not always possible to copy-paste the code while keeping the formatting.

So it would be useful to be able to export the highlighted code as an image.

**Comment by romannurik** [comment]
That should be doable but probably requires an DOM-to-PNG library... marking as help wanted.

**Comment by romannurik** [comment]
For anyone who comes across this, we now have a separate tool for this:
https://snippet.idx.dev/
