### ISSUE TITLE
Text has white highlight when pasted into Slides

### ISSUE THREAD

**Issue by dturner** [romannurik/SlidesCodeHighlighter#5]
Steps to repro: 
- Paste code into syntax highlighter 
- Copy/paste formatted code into Google Slides 

Expected result: 
- Pasted code doesn't have a background or highlight

Actual result:
- Pasted code has a white background

Screenshot:
![image](https://cloud.githubusercontent.com/assets/873212/24969363/77d678b0-1fa8-11e7-8dbc-22479f9bd0ac.png)

**Comment by dturner** [comment]
Dup of #3

**Comment by mavuio** [comment]
in case it helps:

i fixed that in my safari by adding a "custom stylesheet" (via settings/advanced in safari)
and that CSS-rule:

```
div[data-seltreat] .prettyprint {
  background-color: #ffffff01 !important;
}

```
