### ISSUE TITLE
Elif does not highlight properly

### ISSUE THREAD

**Issue by lbiester** [romannurik/SlidesCodeHighlighter#53]
I have noticed that at least in some cases, `elif` does not appear to be highlighted properly by the tool. When I put in the following code, elif is not highlighted:
![image](https://user-images.githubusercontent.com/7333422/91235266-364aa080-e703-11ea-8260-ec26f67cf034.png)

I am willing to try and look into fixing this on my own when I have time, but thought I would bring it to your attention. Thank you for this tool, I use it a lot for teaching!

**Comment by romannurik** [comment]
Hi there! Did you specify python as a language?

**Comment by romannurik** [comment]
Just confirmed this myself, if you set the language to python elif does get highlighted correctly.

**Comment by lbiester** [comment]
Thank you. In my opinion there's a usability issue with the dropdown for language selection. It autofills to `(auto)`, but then when you select the dropdown, it makes it look like there are no other options unless you delete `(auto)`. I initially was unclear on how to actually select the language because of this.

**Comment by romannurik** [comment]
Absolutely agree, it's a pretty simplistic implementation right now. Can definitely improve on it.
