### ISSUE TITLE
Font colour is not preserved on Firefox+GNU/Linux

### ISSUE THREAD

**Issue by Wheest** [romannurik/SlidesCodeHighlighter#55]
Copying highlighted text on Firefox on Linux loses all font colour information.

Does not occur on Chromium.

Firefox version 68.11.0esr.

**Comment by romannurik** [comment]
Hi there! A few things:

1. I can't easily test this, nor can I really guarantee support for various platforms/browsers/etc due to how clipboards work.
2. Where are you pasting into? Google Slides? Something else?

**Comment by pil0u** [comment]
Hey Roman, thanks for the great tool!
Same here, pasting into Google Slides and just like Wheest Chromium works just fine.

When pasting from Firefox, the whole formatting is kept, except for the color. I had no luck after some research online, I have no idea why this happens.

**Comment by Wheest** [comment]
The issue still occurs for me.  To clarify, pasting _into_ Google Slides on Firefox _from_ Chromium preserves the formatting, however copying _from_ the webapp on Firefox loses the colour information.

**Comment by benjaminp** [comment]
Chromium-based browsers automatically inline out-of-line style information on HTML elements copied into the clipboard, but Firefox does not. Presumably, either fixing https://bugzilla.mozilla.org/show_bug.cgi?id=406488 or changing the code highlighter to use inline CSS rather than classes would resolve this issue.

**Comment by romannurik** [comment]
This should now be fixed as part of the shiki+vite rewrite.

**Comment by Wheest** [comment]
> This should now be fixed as part of the shiki+vite rewrite (specifically, we switched to inline styles)

Thanks!
