### ISSUE TITLE
Font size is not preserved when copying into Slides

### ISSUE THREAD

**Issue by dturner** [romannurik/SlidesCodeHighlighter#6]
When copying code into Slides the font size is not preserved. Example: 

Code highlighter shows text at 40pt

![image](https://cloud.githubusercontent.com/assets/873212/24969732/a20125bc-1fa9-11e7-85f3-f54ab1d161a2.png)

But pasting into Slides text is set at 30pt

![image](https://cloud.githubusercontent.com/assets/873212/24969754/b44f95aa-1fa9-11e7-8d33-b31da2dcd014.png)

**Comment by romannurik** [comment]
Gah, not sure if there's much I can do about this :-/

**Comment by romannurik** [comment]
Yeah I think Google Slides does a px --> pt conversion, and I'm not sure it's worth updating this unless Keynote also does this conversion
