### ISSUE TITLE
Python?

### ISSUE THREAD

**Issue by ybagdasa** [romannurik/SlidesCodeHighlighter#62]
Python doesn't seem to be supported...

**Comment by romannurik** [comment]
It may not be autodetected but you should definitely be able to set the language to python in the drop-down.

**Comment by romannurik** [comment]
Definitely let me know if you try that and it doesn't work! (Please include a screenshot if so)

**Comment by ybagdasa** [comment]
![Screenshot from 2021-05-31 17-24-08](https://user-images.githubusercontent.com/5349813/120251037-136e8f00-c235-11eb-9195-4cd8ee4434c6.png)
It only gives 'auto' as the language option for me.

**Comment by romannurik** [comment]
Ah yes just delete auto from the text field and replace it with python.

**Comment by ybagdasa** [comment]
Oh, interesting...I just noticed that I can type in a language option and when I type in 'python' it works...
