### ISSUE TITLE
Support query parameters to fillout output options

### ISSUE THREAD

**Issue by loicortola** [romannurik/SlidesCodeHighlighter#67]
Hello,

thanks for the amazing lib. Simple and beautiful.
We are using it a lot to copy-paste code to slides, and everytime I click on the bookmark, I have to adjust the formatted code settings.
It's most of the time always the same settings, so I would love to encode it in the URL.

Does the feature make sense to you?
I may create a PR if so.

Thanks a lot :)

**Comment by romannurik** [comment]
Sorry for the delay — this use case should already be covered by the fact that preferences (even your last code snippet) are persisted in `localStorage` — is this working for you?

**Comment by loicortola** [comment]
Hello,

not really, using local storage is good to persist it to my local machine, but not for sharing it to others :)
