### ISSUE TITLE
bug: No formatted code shows up

### ISSUE THREAD

**Issue by wangela** [romannurik/SlidesCodeHighlighter#68]
When pasting code on the left, no formatted code appears on the right.

Browser: Chrome Version 101.0.4951.64 

Javascript Console says:

- [error] The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
- [warning] index.js:12 Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/microsoft/monaco-editor#faq
  - Visiting that page shows: I see the warning "Could not create web worker". What should I do? HTML5 does not allow pages loaded on file:// to create web workers. Please load the editor with a web server on http:// or https:// schemes.
- [warning] index.js:12 You must define a function MonacoEnvironment.getWorkerUrl or MonacoEnvironment.getWorker

**Comment by wangela** [comment]
That's an odd symptom - the "Language" element shows "(auto)" in red and the dropdown doesn't expand to show the usual list of options. Is that a clue as to what's failing?
![image](https://user-images.githubusercontent.com/5506675/170140948-585dfaa8-5348-4792-a9f9-c167351292b5.png)

**Comment by romannurik** [comment]
Ah, this is probably because "(auto)" is a left over stored value (in the browser's `localStorage`). try just deleting it entirely? That field doesn't have the best UX :-/
