### ISSUE TITLE
Apex syntax highlighting

### ISSUE THREAD

**Issue by albarivas** [romannurik/SlidesCodeHighlighter#78]
Hi, would it be possible to add Apex syntax highlighting (Salesforce)? I see it's supported in prism, so it would be a matter of including it in the instance you're running!

Thanks!

**Comment by albarivas** [comment]
Hi, any help here @romannurik ?? Thank you!!

**Comment by romannurik** [comment]
apologies for the long delay... I see apex as an option in the language picker.. is that what you mean?

**Comment by albarivas** [comment]
I see it's now available, thank you!
