### ISSUE TITLE
Question about usage of 'bower'

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/SlidesCodeHighlighter#8]
Hey Roman,

I was trying to learn from your web apps again and I was just wondering what is the purpose of using 'bower' in this web app? Couldn't you just add google-code-prettify, ace-builds, and jquery as npm dependencies in package.json and remove bower from the project entirely? Just wondering...

**Comment by romannurik** [comment]
Yeah bower is deprecated in favor of nom+webpack. For really, really simple projects like this one bower easier to setup IMO and is still better than downloading JS libraries manually.

**Comment by alexjlockwood** [comment]
What I mean though is couldn't you just add the deps declared in `bower.json` into `package.json` and then reference the libraries under `node_modules/` instead of `bower_components`?

**Comment by alexjlockwood** [comment]
Then you could use `npm-check-updates` and stuff (not sure if there is something similar for bower as well).

**Comment by romannurik** [comment]
Yep there's bower update I believe
